version: '3'

services:

  # The Web Server
  web:
    container_name: API23P_web
    build: .
    ports:
      - 8055:80
    networks:
          frontend:
              ipv4_address: 172.18.1.3  

    volumes:
      - ./:/var/www/app 

    networks: 
        - mysql56     

networks:
  mysql56:
    external: true
